from enum import Enum, auto

hathceries = {'BAKER LAKE HATCHERY': ('WA_HATCHERY_DATA',), 'BEAVER CREEK HATCHERY': ('WA_HATCHERY_DATA',), 'BINGHAM CREEK HATCHERY': ('WA_HATCHERY_DATA',),
              'BOGACHIEL HATCHERY': ('WA_HATCHERY_DATA',), 'CEDAR RIVER HATCHERY': ('WA_HATCHERY_DATA',), 'CHIWAWA HATCHERY': ('WA_HATCHERY_DATA',),
              'COTTONWOOD CREEK POND': ('WA_HATCHERY_DATA',), 'COWLITZ SALMON HATCHERY': ('WA_HATCHERY_DATA',), 'DUNGENESS HATCHERY': ('WA_HATCHERY_DATA',),
              'EASTBANK HATCHERY': ('WA_HATCHERY_DATA',), 'ELWHA HATCHERY': ('WA_HATCHERY_DATA',), 'FORKS CREEK HARISON HATCHERY': ('WA_HATCHERY_DATA',),
              'GEORGE ADAMS HATCHERY': ('WA_HATCHERY_DATA',), 'HOODSPORT HATCHERY': ('WA_HATCHERY_DATA',), 'HUMPTULIPS HATCHERY': ('WA_HATCHERY_DATA',),
              'HURD CREEK HATCHERY': ('WA_HATCHERY_DATA',), 'ICY CREEK HATCHERY': ('WA_HATCHERY_DATA',), 'ISSAQUAH HATCHERY': ('WA_HATCHERY_DATA',),
              'KENDALL CREEK HATCHERY': ('WA_HATCHERY_DATA',), 'LEWIS RIVER HATCHERY': ('WA_HATCHERY_DATA',), 'LYONS FERRY HATCHERY': ('WA_HATCHERY_DATA',),
              'MARBLEMOUNT HATCHERY': ('WA_HATCHERY_DATA',), 'MCKERNAN HATCHERY': ('WA_HATCHERY_DATA',), 'MINTER CREEK HATCHERY': ('WA_HATCHERY_DATA',),
              'NASELLE HATCHERY': ('WA_HATCHERY_DATA',), 'NEMAH HATCHERY': ('WA_HATCHERY_DATA',), 'NORTH TOUTLE HATCHERY': ('WA_HATCHERY_DATA',),
              'PRIEST RAPIDS HATCHERY': ('WA_HATCHERY_DATA',), 'REITER PONDS': ('WA_HATCHERY_DATA',), 'RINGOLD SPRINGS HATCHERY': ('WA_HATCHERY_DATA',),
              'SAMISH HATCHERY': ('WA_HATCHERY_DATA',), 'SKAMANIA HATCHERY': ('WA_HATCHERY_DATA',), 'SKOOKUMCHUCK HATCHERY': ('WA_HATCHERY_DATA',),
              'SOOS CREEK HATCHERY': ('WA_HATCHERY_DATA',), 'SPEELYAI HATCHERY': ('WA_HATCHERY_DATA',), 'TOKUL CREEK HATCHERY': ('WA_HATCHERY_DATA',),
              'TUCANNON HATCHERY': ('WA_HATCHERY_DATA',), 'TUMWATER FALLS HATCHERY': ('WA_HATCHERY_DATA',), 'VOIGHTS CREEK HATCHERY': ('WA_HATCHERY_DATA',),
              'WASHOUGAL HATCHERY': ('WA_HATCHERY_DATA',), 'FOSTER RD TRAP': ('WA_HATCHERY_DATA',), 'KALAMA FALLS HATCHERY': ('WA_HATCHERY_DATA',),
              'LK ABERDEEN HATCHERY': ('WA_HATCHERY_DATA',), 'MERWIN DAM FCF': ('WA_HATCHERY_DATA',), 'MODROW TRAP': ('WA_HATCHERY_DATA',),
              'SOLDUC HATCHERY': ('WA_HATCHERY_DATA',), 'SUNSET FALLS FCF': ('WA_HATCHERY_DATA',), 'WALLACE R HATCHERY': ('WA_HATCHERY_DATA',),
              'WASHOUGAL RIVER FISH WEIR': ('WA_HATCHERY_DATA',), 'WHITEHORSE POND': ('WA_HATCHERY_DATA',)}


class Hatcheries(Enum):
    WA_HATCHERY_DATA = auto()
