from enum import Enum, auto


class Hatcheries(Enum):
    WA_HATCHERY_DATA = auto()


hathceries = {'BAKER LAKE HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'BEAVER CREEK HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'BINGHAM CREEK HATCHERY': (Hatcheries.WA_HATCHERY_DATA),
              'BOGACHIEL HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'CEDAR RIVER HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'CHIWAWA HATCHERY': (Hatcheries.WA_HATCHERY_DATA),
              'COTTONWOOD CREEK POND': (Hatcheries.WA_HATCHERY_DATA), 'COWLITZ SALMON HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'DUNGENESS HATCHERY': (Hatcheries.WA_HATCHERY_DATA),
              'EASTBANK HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'ELWHA HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'FORKS CREEK HARISON HATCHERY': (Hatcheries.WA_HATCHERY_DATA),
              'GEORGE ADAMS HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'HOODSPORT HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'HUMPTULIPS HATCHERY': (Hatcheries.WA_HATCHERY_DATA),
              'HURD CREEK HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'ICY CREEK HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'ISSAQUAH HATCHERY': (Hatcheries.WA_HATCHERY_DATA),
              'KENDALL CREEK HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'LEWIS RIVER HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'LYONS FERRY HATCHERY': (Hatcheries.WA_HATCHERY_DATA),
              'MARBLEMOUNT HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'MCKERNAN HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'MINTER CREEK HATCHERY': (Hatcheries.WA_HATCHERY_DATA),
              'NASELLE HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'NEMAH HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'NORTH TOUTLE HATCHERY': (Hatcheries.WA_HATCHERY_DATA),
              'PRIEST RAPIDS HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'REITER PONDS': (Hatcheries.WA_HATCHERY_DATA), 'RINGOLD SPRINGS HATCHERY': (Hatcheries.WA_HATCHERY_DATA),
              'SAMISH HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'SKAMANIA HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'SKOOKUMCHUCK HATCHERY': (Hatcheries.WA_HATCHERY_DATA),
              'SOOS CREEK HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'SPEELYAI HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'TOKUL CREEK HATCHERY': (Hatcheries.WA_HATCHERY_DATA),
              'TUCANNON HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'TUMWATER FALLS HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'VOIGHTS CREEK HATCHERY': (Hatcheries.WA_HATCHERY_DATA),
              'WASHOUGAL HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'FOSTER RD TRAP': (Hatcheries.WA_HATCHERY_DATA), 'KALAMA FALLS HATCHERY': (Hatcheries.WA_HATCHERY_DATA),
              'LK ABERDEEN HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'MERWIN DAM FCF': (Hatcheries.WA_HATCHERY_DATA), 'MODROW TRAP': (Hatcheries.WA_HATCHERY_DATA),
              'SOLDUC HATCHERY': (Hatcheries.WA_HATCHERY_DATA), 'SUNSET FALLS FCF': (Hatcheries.WA_HATCHERY_DATA), 'WALLACE R HATCHERY': (Hatcheries.WA_HATCHERY_DATA),
              'WASHOUGAL RIVER FISH WEIR': (Hatcheries.WA_HATCHERY_DATA), 'WHITEHORSE POND': (Hatcheries.WA_HATCHERY_DATA)}
